
Epoch 1/200, Loss: 29.1071
Epoch 2/200, Loss: 8.3928
Epoch 3/200, Loss: 8.4242
Epoch 4/200, Loss: 8.3290
Epoch 5/200, Loss: 7.2947
Epoch 6/200, Loss: 100.4090
Epoch 7/200, Loss: 173.4317
Epoch 8/200, Loss: 173.3025
Epoch 9/200, Loss: 173.0176
Epoch 10/200, Loss: 172.5335
Epoch 11/200, Loss: 173.3084
Epoch 12/200, Loss: 173.0744
Epoch 13/200, Loss: 173.1939
Epoch 14/200, Loss: 173.0658
Epoch 15/200, Loss: 173.0384
Epoch 16/200, Loss: 173.4394
Epoch 17/200, Loss: 172.8457
Epoch 18/200, Loss: 173.4371
Epoch 19/200, Loss: 172.2055
Epoch 20/200, Loss: 172.9317
Epoch 21/200, Loss: 172.2427
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x14d5a35ad310>
Traceback (most recent call last):
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1442, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1790892) is killed by signal: Interrupt.