
Epoch 1, Loss: nan
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x1495648b2550>
Traceback (most recent call last):
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1442, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 400773) is killed by signal: Interrupt.