Traceback (most recent call last):
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 211, in <module>
    main()
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 203, in main
    train_streaming(model, dataloader, num_epochs=args['num_epochs'], lr=args['lr'], rank=rank, device=device)
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 113, in train_streaming
    for theta_batch, x_batch in dataloader:
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 54, in __iter__
    theta = torch.rand(self.theta_dim, device=self.simulator.device)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/cuda/__init__.py", line 235, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
Traceback (most recent call last):
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 211, in <module>
    main()
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 203, in main
    train_streaming(model, dataloader, num_epochs=args['num_epochs'], lr=args['lr'], rank=rank, device=device)
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 113, in train_streaming
    for theta_batch, x_batch in dataloader:
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/pscratch/sd/k/katiekee/PDFParameterInference/cl.py", line 54, in __iter__
    theta = torch.rand(self.theta_dim, device=self.simulator.device)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/torch/cuda/__init__.py", line 235, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method